language: emacs-lisp
env:
  - EMACS=emacs24
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qy "${EMACS}"-nox
  # Install and bootstrap cask
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="${HOME}/.cask/bin:$PATH"
install:
  - cask install
script:
  - cask exec ert-runner